---
sidebar: sidebar 
permalink: calculate-evs-savings.html 
keywords: vm workloads, deploy fsx, deploy storage for vms, evs, savings, calculate, tco 
summary: 计算将 Amazon EVS 与 FSx for ONTAP结合使用可以节省多少。 
---
= 探索使用BlueXP workload factory节省 Amazon Elastic VMware Service 成本的方法
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
探索将 VMware 工作负载迁移到 Amazon Elastic VMware Service (EVS) 的潜在节省空间。该计算器可让您比较使用 Amazon EVS 和不使用Amazon FSx for NetApp ONTAP作为存储的成本。

如果节省计算器确定最具成本效益的存储是 FSx for ONTAP，您可以创建详细的评估，该评估提供了您可以在使用前查看的迁移计划。然后，您可以使用 Codebox 生成 Infrastructure-as-Code 模板。



== 探索 EVS 环境的节省

按照以下步骤探索计划迁移到 Amazon EVS 环境的潜在节省。


NOTE: 在继续之前，请查看储蓄计算器底部的免责声明，以了解有关如何计算价格估算的更多信息。

.步骤
. 使用其中一个登录到工作负载工厂 https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^]。
. 从 VMware 工作负载图块中，选择 *探索节省*，然后选择 *Amazon Elastic VMware Service (EVS)*。显示储蓄计算器。
+
*环境偏好设置*窗格提供了滑块，您可以根据环境需求进行调整。

. 根据需要调整以下滑块以查看您所选值的实时节省计算。如果使用键盘，您可以使用箭头键进行微调：
+
.. *所需物理 CPU（数量）*
.. *所需物理内存 (GiB)*
.. *所需虚拟机存储 (TiB)*
.. *EVS 计费计划*


. 执行以下操作之一：
+
** 使用迁移顾问link:launch-migration-advisor-evs-manual.html["创建部署计划"]对于 Amazon EVS 环境，选择*创建详细评估*。
** 选择“*关闭*”以关闭 TCO 计算器。



