---
sidebar: sidebar 
permalink: deploy-fsx-file-system-evs.html 
keywords: vm workloads, deploy fsx, deploy storage for vms, evs, elastic vmware service 
summary: 在您验证推荐的 FSx for ONTAP文件系统（或在某些情况下的文件系统）满足您的确切要求后，您可以使用 Workload Factory 在您的 AWS 环境中部署该系统。 
---
= 为ONTAP文件系统部署建议的FSx
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
在您验证推荐的 FSx for ONTAP文件系统（或在某些情况下为多个文件系统）满足您的确切要求后，您可以使用 Workload Factory 在您的 AWS 环境中部署该系统。

根据您添加到 Workload Factory 帐户的策略和权限，您可以使用 Workload Factory（使用读/写模式）完全部署 FSx for ONTAP文件系统。如果您拥有的权限较少（只读模式）或没有权限（基本模式），则需要使用 Codebox 中的 CloudFormation 模板并在 AWS 中自行部署 FSx for ONTAP文件系统。



== 要求

* 您必须拥有 Amazon Elastic VMware Service 订阅。
* 您必须拥有必要的权限才能在您的 AWS 账户中创建 FSx for ONTAP 文件系统。




== 注意事项

* 您可以使用快速创建或高级创建选项。高级创建提供了一些其他存储参数、您可以自定义这些参数。 https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["了解这两种选项的功能"](英文)
* 在“Amazon Elastic VMware Service 首选项”部分，您可以选择 EVS 虚拟化环境以连接到外部数据存储。这样会自动填充一些字段，提供部署的最佳实践选项。您可以根据需要更改这些选项。




== 步骤

. 在*Review pland*页面底部，选择*Deploy，此时将显示Create an FSx for ONTAP file system页面。
+
根据您提供的信息、定义FSx for ONTAP文件系统的大多数字段都已完成、但此页面中有几个字段需要完成。

. 在“文件系统常规配置”部分中，输入以下信息：
+
.. *AWS 凭证*：选择或添加凭证，为 Workload Factory 提供直接创建 FSx for ONTAP文件系统所需的权限。您还可以从 Codebox 选择 CloudFormation 代码并在 AWS 中自行部署 FSx for ONTAP文件系统。
.. *文件系统名称*：输入要用于此FSx for ONTAP文件系统的名称。
.. *标签*：您可以选择添加标签来对此 FSx for ONTAP 文件系统进行分类。


. 在“Amazon Elastic VMware Service 首选项”部分，从“环境 ID”列表中选择数据存储将连接的 EVS 环境。
+
此功能会自动填充以下字段：

+
** *VPC*
** *可用区域*
** 子网
** 在“NFS 数据存储访问”部分，如果您选择了“仅 EVS 主机管理”选项，“EVS 主机管理 (CIDR)”字段将自动填充。
** 在“数据存储挂载选项”部分，如果您选择将数据存储挂载到 EVS 集群，则“EVS 集群 VMware vCenter 地址”和“vSphere 管理员凭据密钥 ARN”字段将自动填充。


. 在"网络和安全"部分中、输入以下信息：
+
.. *区域和 VPC*：选择将部署 FSx for ONTAP 文件系统的区域和 VPC。
.. *安全组*（仅限高级创建）：使用“高级创建”选项时，您可以选择 FSx for ONTAP VPC 的默认安全组，以便所有流量都可以访问 FSx for ONTAP 文件系统。您可以创建新的安全组，也可以选择现有的安全组。
+
如果启用*根据 EVS NFS 数据存储调整安全组配置*选项，Workload Factory 将根据 EVS NFS 数据存储的设置配置安全组。

+
您可以向安全组添加入站规则，以限制其他 AWS 服务可以访问 FSx for ONTAP 文件系统。这将减少打开的服务数量。以下是最低端口和协议数量：

+
[cols="15,10,55"]
|===
| 协议 | 端口 | 目的 


| TCP、UDP | 111 | portmaper (用于协商NFS请求中使用的端口) 


| TCP、UDP | 635 | NFS mounta (接收NFS挂载请求) 


| TCP、UDP | 2049 | NFS网络流量 


| TCP、UDP | 4045 | 网络锁定管理器(NLM、lockd)-处理锁定请求。 


| TCP、UDP | 4046 | 网络状态监控器(NSM、statd)—在服务器重新启动以进行锁定管理时通知NFS客户端。 
|===
.. *可用区域*：选择可用区域和子网。
+
如果要避免跨AZ流量产生费用、应选择与VMware SDDC部署位置相同的可用性区域。

.. *加密*（仅限高级创建）：使用*高级创建*选项时，您可以从下拉列表中选择 AWS 加密密钥名称。
.. *NFS 数据存储访问*（仅限高级创建）：使用*高级创建*选项时，您可以选择所有主机是否可以访问数据存储，或者只有 EVS 管理主机可以访问数据存储。


. 在"文件系统详细信息"部分中、输入以下信息：
+
.. *ONTAP 凭据*：输入 ONTAP 用户名密码。
.. * Storage VM凭据*(仅限高级创建)：输入并确认Storage VM密码。密码可以特定于此文件系统、也可以使用为ONTAP凭据输入的相同密码。


. 在“EVS 集群附件”部分中，输入以下信息：
+
.. *数据存储区挂载选项*：可选地，启用*将数据存储区挂载到 EVS 集群*选项以自动将数据存储区连接到 Amazon EVS 集群。此选项还会导致 Workload Factory 配置 VMware ESXi 主机设置，以便它们符合ONTAP最佳实践建议。在部署文件系统之前，您可以查看“*摘要*”部分中的计划详细信息，以查看已更改的设置。
.. *EVS 集群 vSphere 控制台详细信息*：输入应连接到 Amazon EVS 的 VMware vCenter 服务器的 IP 地址或 FQDN。
.. *vSphere 管理员凭据密钥 ARN*：选择 vSphere 管理员凭据密钥 ARN。这些凭据用于挂载数据存储区并配置推荐的 VMware 设置。
+
如果 Amazon EVS 在该区域不可用，或者您的账户没有权限检索可用密钥 ARN 的列表，您可以手动输入密钥 ARN 值。



. 在*摘要*部分中，您可以查看VMware迁移顾问根据您的信息设计的FSx for ONTAP文件系统和数据存储库配置。
. 选择*Create/*以部署FSx for ONTAP文件系统。此过程可能需要长达2小时。
+
或者，在 Codebox 窗口中，您可以选择 *重定向到 CloudFormation* 以使用 CloudFormation 堆栈创建文件系统和推荐的 VM 配置。

+
无论哪种情况，您都可以在 CloudFormation 中监控创建进度。





== 结果

此时将部署FSx for ONTAP文件系统。您现在可以使用 Codebox 中的 AWS CloudFormation 模板将推荐的 VM 配置部署到您的 Amazon Elastic VMware Service 环境。
