---
sidebar: sidebar 
permalink: launch-migration-advisor-evs-manual.html 
keywords: overview, concepts, features, use case, workloads, how Workload Factory works, migration, manual, specification, deploy, deployment, plan 
summary: 登录NetApp Workload Factory 以访问 VMware 规划中心。您可以手动创建 EVS 的部署计划。 
---
= 手动创建 Amazon EVS 的部署计划
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
登录NetApp Workload Factory 以访问 VMware 规划中心。从那里，您可以手动创建根据您的需求定制的 Amazon EVS 部署计划或迁移计划。

请注意，您必须拥有用户名和密码才能访问 Workload Factory。如果您没有访问权限，请立即创建一个帐户。查看说明 https://docs.netapp.com/us-en/workload-setup-admin/quick-start.html["此处"]。



== 通过手动指定环境要求来创建部署计划

您可以手动指定 Amazon Elastic VMware Service 中虚拟机的要求，并使用定制的 Amazon FSx for NetApp ONTAP 文件系统作为外部数据存储。

.要求
* 您必须拥有 Amazon Elastic VMware Service 订阅。


.步骤
. 使用以下方式之一登录 Workload Factory https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["控制台体验"^] 。
. 或者，如果您从 Workload Factory 控制台访问 Workload Factory，请从 VMware 工作负载磁贴中选择 *VMware 规划中心*，然后选择 *VMware 规划中心*。显示 VMware 规划中心。
. 选择*手动创建 EVS 计划*。
. 输入您的 VM 环境的要求。
+
[NOTE]
====
请记住以下虚拟机迁移性能要求和建议：

** 出于性能原因，建议 VM 库存的最小存储容量为 10TiB。
** Amazon Elastic VMware Service 数据存储区需要最小吞吐量，具体取决于您为此部署指定所需的 IOPS 数量。
** 根据 FSx for ONTAP 文件系统配置，Amazon Elastic VMware Service 环境需要最少数量的外部数据存储才能达到最佳性能。


====
. 准备就绪后，选择*审查计划*来审查迁移计划。
. 查看计划。展开每个部分以查看计划详细信息。
+
默认情况下，Workload Factory 将迁移计划保存到规划中心。您可以在页面顶部附近取消选择此选项。

. 或者，当您对迁移计划满意时，您可以通过选择*导出计划（PDF）*将计划详细信息下载为 PDF 文档。
. 当您准备好配置部署计划时，选择*配置*。


link:deploy-fsx-file-system-evs.html["为ONTAP文件系统部署VMware工作负载建议的FSx"](英文)
