---
sidebar: sidebar 
permalink: learn-about-vmware-workloads.html 
keywords: overview, concepts, features, use case, workloads, how Workload Factory works 
summary: 'NetApp Workload Factory for VMware 提供了一些工具，可将您的数据从本地系统迁移到 Amazon EVS、VMware Cloud on AWS (VMC) 或 Amazon EC2。' 
---
= 了解NetApp Workload Factory for VMware
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory for VMware 提供了将数据从本地系统迁移到 Amazon Elastic VMware Service (EVS)、VMware Cloud on AWS (VMC) 或 Amazon EC2 的工具。



== 什么是NetApp Workload Factory for VMware？

NetApp Workload Factory for VMware 提供规划中心和迁移顾问，使您能够分析本地 vSphere 环境中的当前虚拟机配置。然后，迁移顾问会生成一个计划，将推荐的 VM 布局部署到 AWS vSphere 集群上的 Amazon EVS、Amazon EC2 或 VMware Cloud，并使用定制的Amazon FSx for NetApp ONTAP文件系统作为外部数据存储。规划中心充当 VMware 仪表板的工作负载工厂，使您能够管理已保存的 VM 库存数据集和已保存的迁移计划并提供已保存的任何迁移计划。

Amazon FSx for NetApp ONTAP是基于 NetApp 的ONTAP文件系统构建的外部 NFS 数据存储，可以连接到 Amazon EVS 或 Amazon EC2 实例或 VMware Cloud on AWS vSphere 集群。无需添加更多主机来增加可用存储；相反，只需使用 FSx for ONTAP卷作为外部数据存储来补充 vSAN 数据存储。这为您提供了灵活、高性能、虚拟化的存储基础架构，可独立于计算资源进行扩展。

有关 Workload Factory 的更多信息，请参阅 https://docs.netapp.com/us-en/workload-setup-admin/workload-factory-overview.html["工作负载工厂概述"^]。



== VMware 迁移顾问的工作原理

迁移顾问可以帮助您将在任何 VMware 支持的数据存储上运行的本地虚拟机 (VM) 及其数据移动到 Amazon EVS、Amazon EC2 或 VMware Cloud 数据存储，其中包括 FSx for ONTAP文件系统上的补充 NFS 数据存储。

请注意、您最多可以将四(4)个FSx for ONTAP卷连接到基于AWS的VMware Cloud上的一个vSphere集群。



== 移民顾问能为您做些什么

迁移顾问提供以下功能：

* 分析当前的内部VM配置
* 确定要迁移到 Amazon EC2、Amazon EVS 或 VMware Cloud on AWS 的虚拟机
* 确定ONTAP卷在FSx上用作VM外部数据存储库所需的空间
* 查看生成的报告以了解部署步骤
* 执行实际部署


迁移顾问支持针对连接到单个 FSx for ONTAP文件系统的单个 Amazon EVS 或 Amazon EC2 实例或 VMware Cloud on AWS 集群进行配置规划。



== 使用移民顾问的好处

使用Amazon FSx for ONTAP作为外部NFS数据存储库、将当前基础架构的部分内容过渡到Amazon EC2或AWS上的VMware Cloud具有以下优势：

* 主机和存储分离以及高级数据效率功能可优化成本
* 无需购买额外的主机实例、即可根据需要增加存储容量
* 云中的NetApp ONTAP数据管理功能、例如节省空间的快照、克隆、数据压缩、重复数据删除、数据缩减、 和复制
* 减少对硬件更新的管理
* 除了增加或减小卷大小之外、还可以更改数据吞吐量、IOPS和文件系统大小
* 支持多可用性区域(AZ)部署的高可用性
* 通过使用VPC对等而无需使用TransitGateway的单可用性配置降低成本和延迟




== 使用NetApp Workload Factory 的工具

您可以将NetApp Workload Factory 与以下工具一起使用：

* *Workload Factory 控制台*：Workload Factory 控制台提供您的应用程序和项目的可视化、整体视图。
* * NetApp控制台*： NetApp控制台提供混合界面体验，以便您可以将 Workload Factory 与其他NetApp数据服务一起使用。
* *问我*：使用问我 AI 助手来提问并了解有关 Workload Factory 的更多信息，而无需离开 Workload Factory 控制台。从 Workload Factory 帮助菜单访问“问我”。
* *CloudShell CLI*：Workload Factory 包含一个 CloudShell CLI，可通过基于浏览器的单个 CLI 跨账户管理和操作 AWS 和NetApp环境。从 Workload Factory 控制台顶部栏访问 CloudShell。
* *REST API*：使用 Workload Factory REST API 部署和管理您的 FSx for ONTAP文件系统和其他 AWS 资源。
* *CloudFormation*：使用 AWS CloudFormation 代码执行您在 Workload Factory 控制台中定义的操作，以从您的 AWS 账户中的 CloudFormation 堆栈对 AWS 和第三方资源进行建模、配置和管理。
* *Terraform NetApp Workload Factory 提供商*：使用 Terraform 构建和管理在 Workload Factory 控制台中生成的基础架构工作流。




== 成本

使用 Workload Factory for VMware 是免费的。

您需要根据迁移顾问的建议支付所部署的 AWS 资源的费用。



== 许可

无需NetApp的特殊许可即可使用 Workload Factory for VMware。



== 区域

所有支持 FSx for ONTAP 的商业区域均支持 Workload Factory。 https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["查看支持的亚马逊区域。"^]

以下 AWS 区域不受支持：

* 中国地区
* GovCloud（美国）区域
* 秘密云
* 绝密云

