---
settings:
  name: VMware workloads
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: zh-cn,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-tw
sidebar:
  entries:
  - title: VMware工作负载文档
    url: "/index.html"
  - title: 发行说明
    entries:
    - title: 新增功能
      url: "/whats-new.html"
  - title: 开始使用
    entries:
    - title: 了解NetApp Workload Factory for VMware
      url: "/learn-about-vmware-workloads.html"
    - title: 迁移到 Amazon EVS 的快速入门
      url: "/quick-start-evs.html"
    - title: 迁移到Amazon EC2的快速入门
      url: "/quick-start-native.html"
    - title: 迁移到VMware Cloud on AWS的快速入门
      url: "/quick-start.html"
    - title: 探索 VMware 规划中心
      url: "/explore-planning-center.html"
  - title: 使用 VMware 规划中心
    entries:
    - title: 上传虚拟机清单数据
      url: "/upload-vm-inventory.html"
    - title: 迁移到 Amazon Elastic VMware Service
      entries:
      - title: 探索储蓄
        url: "/calculate-evs-savings.html"
      - title: 手动创建部署计划
        url: "/launch-migration-advisor-evs-manual.html"
      - title: 使用迁移顾问创建部署计划
        url: "/launch-migration-advisor-evs.html"
      - title: 为ONTAP文件系统部署建议的FSx
        url: "/deploy-fsx-file-system-evs.html"
    - title: 迁移到Amazon EC2
      entries:
      - title: 使用迁移顾问创建部署计划
        url: "/launch-onboarding-advisor-native.html"
      - title: 为ONTAP文件系统部署建议的FSx
        url: "/deploy-fsx-file-system-native.html"
    - title: 迁移到基于AWS的VMware Cloud
      entries:
      - title: 使用迁移顾问创建部署计划
        url: "/launch-onboarding-advisor.html"
      - title: 为ONTAP文件系统部署建议的FSx
        url: "/deploy-fsx-file-system.html"
      - title: 将FSx for ONTAP连接到AWS上的VMware Cloud
        url: "/connect-sddc-to-fsx.html"
      - title: 将数据迁移到新基础架构
        url: "/migrate-data.html"
  - title: 知识和支持
    entries:
    - title: 注册以获得支持
      url: "/support-registration.html"
    - title: 获取帮助
      url: "/get-help.html"
  - title: 法律声明
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
