---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: 了解 Workload Factory 的 VMware 迁移顾问组件的新功能。 
---
= NetApp Workload Factory for VMware 的新功能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
了解 Workload Factory 的 VMware 迁移顾问组件的新功能。



== 2026年1月4日



=== 问我关于人工智能助手首页集成的问题

Workload Factory 控制台主页嵌入了 Ask me AI 助手，使您可以询问有关您自己的存储环境的问题，直接从您的环境中获取个性化见解，并参考以前的对话。您可以与“问我”进行交互，以了解您的工作负载、解决问题并了解更多关于工作负载工厂的信息——所有这些都无需离开控制台。



== 2025年11月27日



=== 计算迁移到 Amazon Elastic VMware Service 为特定区域节省的成本

现在，您可以探索不同云迁移部署选项的价值，优化解决方案评估方面的投入，并深入了解有可能在云端带来价值和节省的解决方案。

您还可以查看使用 FSx for ONTAP进行 EVS 部署可以节省的 vCPU 核心数。

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["探索使用NetApp Workload Factory 节省 Amazon Elastic VMware Service 成本的方法"]



== 2025年11月2日



=== 在 FSx for ONTAP文件系统部署向导中引入 Amazon Elastic VMware Service 首选项

当您部署 FSx for ONTAP文件系统以用作 Amazon Elastic VMware Service 的外部 NFS 数据存储时，现在可以选择数据存储将连接到的 EVS 环境。此功能会自动填充部署向导中的多个字段，以简化部署过程。

https://docs.netapp.com/us-en/workload-vmware/deploy-fsx-file-system-evs.html["为ONTAP文件系统部署建议的FSx"]



=== VMware 工作负载的权限变更

VMware 工作负载能够更清晰地说明特定操作所需的权限，并允许您精细地选择所需的权限。添加凭据时，您将有两个权限选项可供选择，而不是之前的权限模型（_只读_和_读/写_）。新的权限模型将权限策略分解如下：

* 查看、规划和分析：查看 EVS 虚拟化环境的清单，获取系统架构完善的分析，并探索节省成本的方法。
* 数据存储部署和连接：将推荐的 VM 布局部署到 Amazon EVS、Amazon EC2 或 VMware Cloud on AWS vSphere 集群，并使用定制的Amazon FSx for NetApp ONTAP文件系统作为外部数据存储。


添加凭据时，您可以根据要向 VMware 工作负载提供的访问级别，选择一个或多个权限策略。

link:https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html["Workload Factory 权限参考"^]



=== Amazon EC2迁移顾问改进

此版本的NetApp Workload Factory for VMware 对迁移顾问体验进行了多项改进：

* *保存或下载迁移计划*：您现在可以将迁移计划保存或下载为 PDF 或 CSV 文件。保存迁移计划时，该计划将保存到您的 Workload Factory 帐户中。




== 2025年10月5日



=== BlueXP workload factory现为NetApp工作负载工厂

BlueXP已重命名并重新设计，以更好地反映其在管理数据基础设施中的作用。因此， BlueXP workload factory已重命名为NetApp工作负载工厂。



=== VMware 工作负载规划中心简介

VMware 工作负载规划中心使您能够从一个地方查看和管理您的 VM 库存和迁移计划。您可以从不同的环境上传和保存多个 VM 清单，并开始计划将其中任何一个迁移到 AWS EC2 或 Amazon Elastic VMware 服务。您还可以创建并保存 AWS EC2 或 EVS 迁移计划。

https://docs.netapp.com/us-en/workload-vmware/explore-planning-center.html["探索 VMware 工作负载规划中心"]



=== 引入对 Amazon Elastic VMWare Service 的迁移顾问支持

BlueXP Workload Factory for VMware 现在允许您使用 Amazon Elastic VMware Service 迁移顾问将本地 VMware 工作负载快速迁移到 Amazon Elastic VMware Service。使用迁移顾问创建迁移计划后，该计划会自动保存在规划中心的迁移计划列表中。

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs.html["使用迁移顾问为 Amazon EVS 创建部署计划"]



== 2025年8月3日



=== 改进了对 Amazon Elastic VMWare Service 的迁移顾问支持

NetApp Workload Factory 现在支持自动部署和安装Amazon FSx for NetApp ONTAP文件系统。这样，当迁移到 Amazon EVS 环境完成后，您就可以开始在 FSx for ONTAP文件系统上部署虚拟机。

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["使用迁移顾问为 Amazon EVS 创建部署计划"]



=== 计算迁移到 Amazon Elastic VMware Service 节省的成本

您现在可以探索将 VMware 工作负载迁移到 Amazon Elastic VMware Service (EVS) 的潜在节省。节省计算器可让您比较使用 Amazon EVS 与Amazon FSx for NetApp ONTAP作为底层存储和不使用 Amazon FSx for NetApp ONTAP 作为底层存储的成本。当您调整环境特征时，计算器会实时显示潜在的节省。

https://docs.netapp.com/us-en/workload-vmware/calculate-evs-savings.html["探索使用BlueXP Workload Factory 节省 Amazon Elastic VMware Service 成本的方法"]



== 2025年6月29日



=== 引入对 Amazon Elastic VMWare Service 的迁移顾问支持

BlueXP Workload Factory for VMware 现在支持 Amazon Elastic VMware Service。您可以手动将本地 VMware 工作负载迁移到 Amazon Elastic VMware Service，从而优化成本并更好地控制您的 VMware 环境，而无需重构或重新平台化您的应用程序。

https://docs.netapp.com/us-en/workload-vmware/launch-migration-advisor-evs-manual.html["使用迁移顾问为 Amazon EVS 创建部署计划"]



== 2025年5月4日



=== Amazon EC2迁移顾问改进

此版本的BlueXP Workload Factory for VMware 对 Amazon EC2 迁移顾问体验进行了以下改进：

*将NetApp数据基础架构洞察作为数据源*：现在、工作负载工厂可直接与NetApp数据基础架构洞察连接、以便在使用EC2迁移顾问数据收集器时收集VMware部署信息。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



=== 更新了权限术语

Workload Factory 用户界面和文档现在使用“只读”来指代读取权限，使用“读/写”来指代自动化权限。



== 2025年3月30日



=== Amazon EC2迁移顾问改进

此版本的BlueXP Workload Factory for VMware 对 Amazon EC2 迁移顾问体验进行了多项改进：

* *增强的卷分配指导*：EC2迁移顾问的"分类"和"打包"步骤中的卷分配信息增强了可读性和可用性。系统会显示有关每个卷的更多有用信息、使您能够更好地识别卷并确定如何分配卷。
* *提高了数据收集器脚本的效率*：在为小型VM部署收集数据时、EC2迁移顾问数据收集器脚本可优化CPU利用率。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



== 2025年3月2日



=== Amazon EC2迁移顾问改进

此版本的BlueXP Workload Factory for VMware 对 Amazon EC2 迁移顾问体验进行了多项改进：

* *估计实例类型*：迁移顾问现在可以检查您的环境要求、并为每个VM提供估计的Amazon EC2实例类型。您可以选择在迁移顾问的范围步骤中包括每个VM的估计实例类型。
* *推荐Amazon EBS卷的能力*：由于特定地区的特定容量或性能需求、迁移顾问现在可以建议将数据卷迁移到Amazon Elelic Block Store (EBS)、而不是Amazon FSx for NetApp ONTAP。
* *增强型文件系统自动分配*：Amazon FSx for NetApp ONTAP文件系统分配已得到改进、可以更好地优化成本并最大限度地降低吞吐量。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



== 2025年1月5日



=== Amazon EC2迁移顾问改进

此版本的BlueXP Workload Factory for VMware 对迁移顾问体验进行了多项改进：

* *保存或下载迁移计划*：您现在可以保存或下载迁移计划，并加载迁移计划以填充迁移顾问。当您保存迁移计划时，该计划将与您的 Workload Factory 帐户一起保存。
* *改进的 VM 选择*：适用于 VMware 的BlueXP Workload Factory 现在支持过滤和搜索您想要包含在迁移部署中的 VM 列表。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



== 2024年12月1日



=== Amazon EC2迁移顾问改进

此版本的NetApp Workload Factory for VMware 对迁移顾问体验进行了多项改进：

* *数据收集*：当您使用迁移顾问时， BlueXP Workload Factory for VMware 支持收集特定时间段的数据的功能。
* *VM 选择*：适用于 VMware 的BlueXP Workload Factory 现在支持选择您想要包含在迁移部署中的 VM。
* *快速与高级体验*：使用迁移顾问时，您现在可以选择使用RVtools的快速迁移体验或使用迁移顾问数据收集器的高级体验。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



== 2024年11月3日



=== VMware迁移顾问数据精简率帮助

此版本的Workload Factory for VMware具有一个数据精简率助手。在准备加入AWS云时、数据精简率助手可帮助您确定最适合您的VMware库存和存储资产的比率。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



== 2024年9月19日



=== VMware迁移顾问增强功能

此版本的 VMware Workload Factory 具有功能和稳定性增强功能，以及在使用 VMware 迁移顾问时导入和导出迁移计划的功能。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



== 2024年9月1日



=== 迁移到Amazon EC2

VMware的工作负载工厂现在支持使用VMware迁移顾问迁移到Amazon EC2。



== 2024年7月7日



=== VMware Workload Factory 的初始版本

初始版本支持使用VMware迁移顾问分析内部vSphere环境中的当前虚拟机配置、并生成一个计划、以便将建议的虚拟机布局部署到VMware Cloud on AWS中、并将适用于NetApp ONTAP文件系统的自定义Amazon FSx用作外部数据存储库。
