---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes' 
summary: 了解工作负载工厂的VMware迁移顾问组件的新增功能。 
---
= 适用于VMware的BlueXP  工作负载工厂新增功能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
了解工作负载工厂的VMware Cloud迁移顾问组件的新增功能。



== 2025年1月5日



=== Amazon EC2迁移顾问改进

此版本的适用于VMware的BlueXP  工作负载工厂对迁移顾问体验进行了多项改进：

* *保存或下载迁移计划*：现在可以保存或下载迁移计划，并加载迁移计划以填充迁移顾问。保存迁移计划时、该计划将与您的工作负载工厂帐户一起保存。
* *改进的虚拟机选择*：适用于VMware的BlueXP  工作负载工厂现在支持筛选和搜索要包含在迁移部署中的虚拟机列表。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



== 2024年12月1日



=== Amazon EC2迁移顾问改进

此版本的适用于VMware的BlueXP  工作负载工厂对迁移顾问体验进行了多项改进：

* *数据收集*：BlueXP  Workload Factory for VMware支持在使用迁移顾问时收集特定时间段的数据。
* *虚拟机选择*：适用于VMware的BlueXP  工作负载工厂现在支持选择要包括在迁移部署中的虚拟机。
* *快速与高级体验*：使用迁移顾问时，您现在可以选择使用RVtools的快速迁移体验或使用迁移顾问数据收集器的高级体验。


https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



== 2024年11月3日



=== VMware迁移顾问数据精简率帮助

此版本的Workload Factory for VMware具有一个数据精简率助手。在准备加入AWS云时、数据精简率助手可帮助您确定最适合您的VMware库存和存储资产的比率。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]= 2024年9月19日



=== VMware迁移顾问增强功能

此版本的适用于VMware的工作负载工厂提供了一些功能和稳定性增强功能、并且能够在使用VMware迁移顾问时导入和导出迁移计划。

https://docs.netapp.com/us-en/workload-vmware/launch-onboarding-advisor-native.html["使用迁移顾问为Amazon EC2创建部署计划"]



== 2024年9月1日



=== 迁移到Amazon EC2

VMware的工作负载工厂现在支持使用VMware迁移顾问迁移到Amazon EC2。



== 2024年7月7日



=== VMware工作负载工厂的初始版本

初始版本支持使用VMware迁移顾问分析内部vSphere环境中的当前虚拟机配置、并生成一个计划、以便将建议的虚拟机布局部署到VMware Cloud on AWS中、并将适用于NetApp ONTAP文件系统的自定义Amazon FSx用作外部数据存储库。
